parameters:
    locale: en

imports:
    # general
    - { resource: parameters.yml }
    - { resource: security.yml }

    # vendor bundles
    - { resource: bundle/doctrine.yml }
    - { resource: bundle/framework.yml }
    - { resource: bundle/swiftmailer.yml }
    - { resource: bundle/twig.yml }
