services:

    app.manager.credit_card:
        class: AppBundle\Manager\CreditCardManager
        arguments:
            - "@app.repository.credit_card"
            - "@validator"
            - "@app.utility.card_type"

    app.repository.credit_card:
        class: AppBundle\Repository\CreditCardRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\CreditCard

    app.subscriber.encyption:
        class: AppBundle\Subscriber\EncryptionSubscriber
        arguments:
            - "@annotations.reader"
            - "@app.utility.encryption"
        tags:
            - { name: doctrine.event_subscriber }

    app.utility.algorithm:
        class: AppBundle\Utility\AlgorithmUtility

    app.utility.card_type:
        class: AppBundle\Utility\CardTypeUtility

    app.utility.encryption:
        class: AppBundle\Utility\EncryptionUtility
        arguments:
            - "%aes_key%"

    app.validator.credit_card_numer:
        class: AppBundle\Validator\CreditCardNumberValidator
        arguments:
            - "@app.utility.algorithm"
            - "@app.utility.card_type"
        tags:
            - { name: validator.constraint_validator, alias: credit_card_number_validator }